/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef radius_CONSTANTS_H
#define radius_CONSTANTS_H

#include "radius_types.h"

namespace RadiusThrift {

class radiusConstants {
 public:
  radiusConstants();

};

extern const radiusConstants g_radius_constants;

} // namespace

#endif
