/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "radius_constants.h"

namespace RadiusThrift {

const radiusConstants g_radius_constants;

radiusConstants::radiusConstants() {
}

} // namespace

